#!/bin/bash

helper ()
{
   echo "Syntax:"
   echo
   echo "getinfo <vcf> <samplename> <chr> <pos>"
   echo
}

while getopts ":h" option; do
   case $option in
         h)
         helper
         exit;;
   esac
done

vcf=$1
sample=$2
chr=$3
pos=$4


vcf_head=( $(cat $vcf | grep -m 1 "#CHR") )

for i in "${!vcf_head[@]}"; do

if [[ "${vcf_head[$i]}" == "${sample}" ]]; then
  
  i=$(($i+1))
  str=$(awk -v chr="$chr" -v pos="$pos" -v i="$i" '{if($1==chr && $2==pos) {print $1"\t"$2"\t"$4"\t"$5"\t"$i;{exit}}}' $vcf)
  printf "CHR POS REF ALT GEN_$sample\n$str\n"

 fi
done
